void menu();
void newGame();
void loadGame();
void play(const int height,const int width,const int bombs);
void createDisplay(const int height, const int width, const int bombs);
void createAnswer(const int height, const int width, const int bombs);
void openBlankCell(int i, int j, int height, int width);
void openNumCell(int x, int y);
void loseGame(int x, int y,const int height, const int width, const int bombs);
bool checkWin(const int height, const int width, const int bombs);
void clickOpenedNumCell(int x, int y, int height, int width,int bombs);
void highScoreSave(int data, const int height, const int width, const int bombs);
void highScoreDisplay();
void PlayAgain(const int height, const int width, const int bombs);
void PlayGame(int height,int width, int bombs);
void custom();